#!/usr/bin/env python3
"""Take Some / North Star Engine script environment generator.

Python validates/discovers paths and writes a repo-local CMD file. The CMD shim
must `call` the generated file because child processes cannot mutate the parent
cmd.exe environment directly.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from takesome import apply_delete_list, scan_and_cache_tools
    from takesome.paths import suite_path, suite_root
except Exception:  # pragma: no cover - bootstrap fallback
    apply_delete_list = None
    scan_and_cache_tools = None

    def suite_root(project_root: Path) -> Path:
        return project_root.resolve() / ".takesome"

    def suite_path(project_root: Path, *parts: str) -> Path:
        return suite_root(project_root).joinpath(*parts)


def _cmd_value(value: str) -> str:
    return str(value).replace("%", "%%")


def _cmd_path(path: Path) -> str:
    return _cmd_value(str(path))


def _write_env_cmd(
    path: Path,
    *,
    repo_root: Path,
    engine_root: Path,
    plugin_dir: Path,
    script_root: Path,
    suite_dir: Path,
    python_cmd: str,
    suite_version: str,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    codec_dir = plugin_dir / "codecs"
    lines = [
        "@echo off",
        "rem Generated by tools\\scripts\\init_script_env.py. Do not edit by hand.",
        "rem Re-open suite.bat after moving the repository.",
        "set \"NEWENGINE_SCRIPT_ENV=1\"",
        "set \"NEWENGINE_SCRIPT_ENV_NAME=TakeSome.ScriptEnv\"",
        "set \"NEWENGINE_SCRIPT_ENV_VERSION=4\"",
        f"set \"NEWENGINE_REPO_ROOT={_cmd_path(repo_root)}\"",
        f"set \"NEWENGINE_PROJECT_ROOT={_cmd_path(repo_root)}\"",
        f"set \"NEWENGINE_SUITE_ROOT={_cmd_path(suite_dir)}\"",
        f"set \"TAKESOME_SUITE_ROOT={_cmd_path(suite_dir)}\"",
        f"set \"NEWENGINE_SUITE_VERSION={_cmd_value(suite_version)}\"",
        f"set \"NEWENGINE_ROOT={_cmd_path(engine_root)}\"",
        f"set \"NEWENGINE_PLUGIN_DIR={_cmd_path(plugin_dir)}\"",
        f"set \"NEWENGINE_CODEC_PLUGIN_DIR={_cmd_path(codec_dir)}\"",
        f"set \"NEWENGINE_SCRIPT_ROOT={_cmd_path(script_root)}\"",
        f"set \"NEWENGINE_TOOL_CACHE_DIR={_cmd_path(suite_dir / 'tools')}\"",
        f"set \"NEWENGINE_TOOL_REGISTRY_CACHE={_cmd_path(suite_dir / 'tools' / 'tool-registry.json')}\"",
        f"set \"NEWENGINE_SCRIPT_ENV_FILE={_cmd_path(path)}\"",
        f"set \"NEWENGINE_PYTHON_CMD={_cmd_value(python_cmd)}\"",
        "set \"CARGO_TERM_COLOR=never\"",
        "set \"PYTHONUTF8=1\"",
        "if not defined NEWENGINE_TERMINAL_TYPEWRITER set \"NEWENGINE_TERMINAL_TYPEWRITER=0\"",
        "if not defined NEWENGINE_TERMINAL_TYPEWRITER_DELAY_MS set \"NEWENGINE_TERMINAL_TYPEWRITER_DELAY_MS=0\"",
        "exit /b 0",
        "",
    ]
    path.write_text("\r\n".join(lines), encoding="utf-8")



def _default_suite_version() -> str:
    try:
        from takesome.suite.shell import SUITE_VERSION  # type: ignore

        return str(SUITE_VERSION)
    except Exception:
        return "0.5.2"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Generate Take Some / North Star Engine script env CMD file.")
    parser.add_argument("--repo-root", required=True, help="Repository root path.")
    parser.add_argument("--emit-cmd", required=True, help="Generated CMD env file path.")
    parser.add_argument("--suite-root", default="", help="Optional external Take Some suite/work-state root. Defaults to repo/.takesome.")
    parser.add_argument("--python-cmd", default="python", help="Python command string used by launchers.")
    parser.add_argument("--suite-version", default="", help="Suite version expected by the caller; written into script-env.cmd.")
    args = parser.parse_args(argv)
    suite_version = str(args.suite_version or "").strip() or _default_suite_version()

    repo_root = Path(args.repo_root).resolve()
    engine_root = repo_root / "NewEngine" / "neocore2"
    plugin_source_root = repo_root / "Plugins"
    plugin_dir = engine_root / "plugins"
    script_root = repo_root / "tools" / "scripts"
    emit_cmd = Path(args.emit_cmd).resolve()
    suite_dir = Path(args.suite_root).expanduser().resolve() if str(args.suite_root or "").strip() else suite_root(repo_root)

    if apply_delete_list is not None:
        rc = apply_delete_list(repo_root)
        if rc != 0:
            print("[WARN] DELETE_FILES.txt migration reported warnings; continuing env generation.")

    cargo_toml = engine_root / "Cargo.toml"
    if not cargo_toml.exists():
        print("[WARN] Take Some Script Env was not installed.")
        print(f"[WARN] Engine workspace was not found: {cargo_toml}")
        print("[WARN] Open suite.bat from the project root; it will initialize the suite automatically.")
        return 11

    if not plugin_source_root.exists():
        print("[WARN] Take Some Script Env was not installed.")
        print(f"[WARN] Plugin source directory was not found: {plugin_source_root}")
        print("[WARN] Repository layout is incomplete or the script is not in repo root.")
        return 12

    if not script_root.exists():
        print("[WARN] Take Some Script Env was not installed.")
        print(f"[WARN] Script root was not found: {script_root}")
        return 13

    try:
        plugin_dir.mkdir(parents=True, exist_ok=True)
        (plugin_dir / "codecs").mkdir(parents=True, exist_ok=True)
        suite_dir.mkdir(parents=True, exist_ok=True)
        if scan_and_cache_tools is not None:
            scan_and_cache_tools(repo_root)
        _write_env_cmd(
            emit_cmd,
            repo_root=repo_root,
            engine_root=engine_root,
            plugin_dir=plugin_dir,
            script_root=script_root,
            suite_dir=suite_dir,
            python_cmd=args.python_cmd,
            suite_version=suite_version,
        )
    except OSError as exc:
        print("[WARN] Take Some Script Env was not installed.")
        print(f"[WARN] Failed to create environment files/directories: {exc}")
        return 14

    print("[OK] Take Some Script Env file generated.")
    print(f"[OK] ENV CMD = {emit_cmd}")
    print(f"[OK] REPO    = {repo_root}")
    print(f"[OK] ENGINE  = {engine_root}")
    print(f"[OK] PLUGINS = {plugin_dir}")
    print(f"[OK] SUITE   = {suite_dir}")
    print(f"[OK] TOOLS   = {suite_dir / 'tools' / 'tool-registry.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
