#!/usr/bin/env python3
"""NorthStarSuite script environment generator.

Python validates/discovers paths and writes a generated CMD file. The CMD shim
must `call` the generated file because child processes cannot mutate the parent
cmd.exe environment directly.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

try:
    from noesis.suite import apply_delete_list, scan_and_cache_tools
    from noesis.suite.paths import engine_core_root, engine_repo_root, plugins_root, suite_root
except Exception:  # pragma: no cover - bootstrap fallback
    apply_delete_list = None
    scan_and_cache_tools = None

    def _is_engine_repo(path: Path) -> bool:
        return (path / "NewEngine" / "neocore2" / "Cargo.toml").exists() and (path / "Plugins" / "build_manifest.json").exists()

    def engine_repo_root(project_root: Path) -> Path:
        nested = project_root.resolve() / "EngineRepo"
        return nested.resolve() if _is_engine_repo(nested) else project_root.resolve()

    def engine_core_root(project_root: Path) -> Path:
        return engine_repo_root(project_root) / "NewEngine" / "neocore2"

    def plugins_root(project_root: Path) -> Path:
        return engine_repo_root(project_root) / "Plugins"

    def suite_root(project_root: Path) -> Path:
        candidate = Path(r"D:\\TakeSomeData")
        if candidate.exists() and candidate.is_dir() and (candidate / "dataSet").exists():
            return candidate.resolve()
        return project_root.resolve() / ".takesome"


def _cmd_value(value: str) -> str:
    return str(value).replace("%", "%%")


def _cmd_path(path: Path) -> str:
    return _cmd_value(str(path))


def _write_env_cmd(
    path: Path,
    *,
    project_root: Path,
    source_root: Path,
    engine_root: Path,
    plugin_dir: Path,
    script_root: Path,
    suite_dir: Path,
    python_cmd: str,
    suite_version: str,
) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    codec_dir = plugin_dir / "codecs"
    lines = [
        "@echo off",
        "rem Generated by python -m noesis script-env. Do not edit by hand.",
        "rem Re-open suite.bat after moving the repository or EngineRepo.",
        "set \"NEWENGINE_SCRIPT_ENV=1\"",
        "set \"NEWENGINE_SCRIPT_ENV_NAME=NorthStarSuite.ScriptEnv\"",
        "set \"NEWENGINE_SCRIPT_ENV_VERSION=5\"",
        f"set \"NEWENGINE_REPO_ROOT={_cmd_path(project_root)}\"",
        f"set \"NEWENGINE_PROJECT_ROOT={_cmd_path(project_root)}\"",
        f"set \"NORTHSTAR_ENGINE_REPO={_cmd_path(source_root)}\"",
        f"set \"NEWENGINE_SUITE_ROOT={_cmd_path(suite_dir)}\"",
        f"set \"NORTHSTAR_SUITE_ROOT={_cmd_path(suite_dir)}\"",
        f"set \"TAKESOME_SUITE_ROOT={_cmd_path(suite_dir)}\"",
        f"set \"NEWENGINE_SUITE_VERSION={_cmd_value(suite_version)}\"",
        f"set \"NEWENGINE_ROOT={_cmd_path(engine_root)}\"",
        f"set \"NEWENGINE_PLUGIN_DIR={_cmd_path(plugin_dir)}\"",
        f"set \"NEWENGINE_CODEC_PLUGIN_DIR={_cmd_path(codec_dir)}\"",
        f"set \"NEWENGINE_SCRIPT_ROOT={_cmd_path(script_root)}\"",
        f"set \"NEWENGINE_TOOL_CACHE_DIR={_cmd_path(suite_dir / 'tools')}\"",
        f"set \"NEWENGINE_TOOL_REGISTRY_CACHE={_cmd_path(suite_dir / 'tools' / 'tool-registry.json')}\"",
        f"set \"NEWENGINE_SCRIPT_ENV_FILE={_cmd_path(path)}\"",
        f"set \"NEWENGINE_PYTHON_CMD={_cmd_value(python_cmd)}\"",
        "set \"CARGO_TERM_COLOR=never\"",
        "set \"PYTHONUTF8=1\"",
        f"set \"TEMP={_cmd_path(suite_dir / 'temp')}\"",
        f"set \"TMP={_cmd_path(suite_dir / 'temp')}\"",
        "if not defined NEWENGINE_TERMINAL_TYPEWRITER set \"NEWENGINE_TERMINAL_TYPEWRITER=0\"",
        "if not defined NEWENGINE_TERMINAL_TYPEWRITER_DELAY_MS set \"NEWENGINE_TERMINAL_TYPEWRITER_DELAY_MS=0\"",
        "exit /b 0",
        "",
    ]
    path.write_text("\r\n".join(lines), encoding="utf-8")


def _default_suite_version() -> str:
    try:
        from noesis.suite.suite.shell import SUITE_VERSION  # type: ignore

        return str(SUITE_VERSION)
    except Exception:
        return "0.6.4"


def main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(description="Generate NorthStarSuite script env CMD file.")
    parser.add_argument("--repo-root", required=True, help="Suite host / workspace root path.")
    parser.add_argument("--emit-cmd", required=True, help="Generated CMD env file path.")
    parser.add_argument("--suite-root", default="", help="Optional external NorthStarSuite work-state root. Defaults to repo/.takesome.")
    parser.add_argument("--python-cmd", default="python", help="Python command string used by launchers.")
    parser.add_argument("--suite-version", default="", help="Suite version expected by the caller; written into script-env.cmd.")
    args = parser.parse_args(argv)
    suite_version = str(args.suite_version or "").strip() or _default_suite_version()

    project_root = Path(args.repo_root).resolve()
    source_root = engine_repo_root(project_root)
    engine_root = engine_core_root(project_root)
    plugin_source_root = plugins_root(project_root)
    plugin_dir = engine_root / "plugins"
    script_root = project_root / "noesis"
    emit_cmd = Path(args.emit_cmd).resolve()
    suite_dir = Path(args.suite_root).expanduser().resolve() if str(args.suite_root or "").strip() else suite_root(project_root)

    if apply_delete_list is not None:
        rc = apply_delete_list(project_root)
        if rc != 0:
            print("[WARN] DELETE_FILES.txt migration reported warnings; continuing env generation.")

    cargo_toml = engine_root / "Cargo.toml"
    if not cargo_toml.exists():
        print("[WARN] Engine workspace was not found; generating Suite-only Script Env.")
        print(f"[WARN] Missing optional engine workspace: {cargo_toml}")
        engine_root = project_root
        plugin_source_root = project_root / "Plugins"
        plugin_dir = suite_dir / "plugins"

    if not plugin_source_root.exists():
        print("[WARN] Plugin source directory was not found; continuing with Suite-local plugin directory.")
        print(f"[WARN] Missing optional plugin source directory: {plugin_source_root}")
        plugin_dir = suite_dir / "plugins"

    try:
        plugin_dir.mkdir(parents=True, exist_ok=True)
        (plugin_dir / "codecs").mkdir(parents=True, exist_ok=True)
        suite_dir.mkdir(parents=True, exist_ok=True)
        (suite_dir / "temp").mkdir(parents=True, exist_ok=True)
        (suite_dir / "dataSet").mkdir(parents=True, exist_ok=True)
        if scan_and_cache_tools is not None:
            scan_and_cache_tools(project_root)
        _write_env_cmd(
            emit_cmd,
            project_root=project_root,
            source_root=source_root,
            engine_root=engine_root,
            plugin_dir=plugin_dir,
            script_root=script_root,
            suite_dir=suite_dir,
            python_cmd=args.python_cmd,
            suite_version=suite_version,
        )
    except OSError as exc:
        print("[WARN] NorthStarSuite Script Env was not installed.")
        print(f"[WARN] Failed to create environment files/directories: {exc}")
        return 14

    print("[OK] NorthStarSuite Script Env file generated.")
    print(f"[OK] ENV CMD     = {emit_cmd}")
    print(f"[OK] SUITE_ROOT  = {suite_dir}")
    print(f"[OK] HOST_ROOT   = {project_root}")
    print(f"[OK] ENGINE_REPO = {source_root}")
    print(f"[OK] ENGINE      = {engine_root}")
    print(f"[OK] PLUGINS     = {plugin_dir}")
    print(f"[OK] TOOLS       = {suite_dir / 'tools' / 'tool-registry.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
