from __future__ import annotations

from typing import Any, Dict, List

from . import bridge_restart, dataset, memory, operator_fs, operator_tools, repo, status, workflow
from .tool_registry import build_project_tool_specs
from .auth import forget_key, openai_env, openai_status
from .contracts import BridgeContext, ToolSpec
from .suite import run_takesome, suite_command


def schema(props: Dict[str, Any] | None = None, required: List[str] | None = None) -> Dict[str, Any]:
    return {"type": "object", "properties": props or {}, "required": required or [], "additionalProperties": False}


def build_tools(ctx: BridgeContext) -> Dict[str, ToolSpec]:
    def bind(fn):
        return lambda args: fn(ctx, args)

    specs = {
        "northstar.operator_fs_list_dir": ("Read-only bounded directory listing through the operator filesystem layer.", schema({"path": {"type": "string"}, "limit": {"type": "integer"}, "include_skipped": {"type": "boolean"}}), operator_fs.list_dir),
        "northstar.operator_fs_read_file": ("Read-only bounded UTF-8 text file read through the operator filesystem layer.", schema({"path": {"type": "string"}, "max_bytes": {"type": "integer"}, "offset": {"type": "integer"}}, ["path"]), operator_fs.read_file),
        "northstar.operator_fs_search_text": ("Read-only bounded text search through the operator filesystem layer.", schema({"query": {"type": "string"}, "roots": {"type": "array", "items": {"type": "string"}}, "root": {"type": "array", "items": {"type": "string"}}, "glob": {"type": "array", "items": {"type": "string"}}, "limit": {"type": "integer"}, "regex": {"type": "boolean"}, "case_sensitive": {"type": "boolean"}}, ["query"]), operator_fs.search_text),
        "northstar.operator_fs_file_stat": ("Read-only file stat through the operator filesystem layer.", schema({"paths": {"type": "array", "items": {"type": "string"}}}, ["paths"]), operator_fs.file_stat),
        "northstar.operator_fs_tree": ("Read-only bounded tree listing through the operator filesystem layer.", schema({"path": {"type": "string"}, "depth": {"type": "integer"}, "limit": {"type": "integer"}}), operator_fs.tree),
        "northstar.operator_fs_count_lines": ("Read-only bounded source line counter through the operator filesystem layer.", schema({"roots": {"type": "array", "items": {"type": "string"}}, "root": {"type": "array", "items": {"type": "string"}}, "glob": {"type": "array", "items": {"type": "string"}}, "limit": {"type": "integer"}}), operator_fs.count_lines),
        "northstar.repo_status": ("Return git status as structured diagnostics.", schema({"timeout_sec": {"type": "integer"}}), operator_tools.repo_status),
        "northstar.repo_diff": ("Return bounded git diff output, optionally scoped to paths.", schema({"paths": {"type": "array", "items": {"type": "string"}}, "max_bytes": {"type": "integer"}, "timeout_sec": {"type": "integer"}}), operator_tools.repo_diff),
        "northstar.repo_changed_files": ("Return changed and untracked repository files.", schema({"include_untracked": {"type": "boolean"}}), operator_tools.repo_changed_files),
        "northstar.repo_patch_preview": ("Validate and summarize a unified patch without applying it.", schema({"patch_text": {"type": "string"}, "patch_path": {"type": "string"}, "timeout_sec": {"type": "integer"}}), operator_tools.repo_patch_preview),
        "northstar.repo_patch_apply": ("Apply a validated unified patch. Requires write/sudo mode.", schema({"patch_text": {"type": "string"}, "patch_path": {"type": "string"}, "dry_run": {"type": "boolean"}, "timeout_sec": {"type": "integer"}}), operator_tools.repo_patch_apply),
        "northstar.validate_python_changed": ("Compile changed Python files or explicit Python paths.", schema({"paths": {"type": "array", "items": {"type": "string"}}}), operator_tools.validate_python_changed),
        "northstar.bridge_inspect_tool_descriptors": ("Inspect public MCP tool descriptors, annotations and North Star risk tiers.", schema({"query": {"type": "string"}}), operator_tools.bridge_inspect_tool_descriptors),
        "northstar.repo_search_text": ("Search repository text with context lines.", schema({"query": {"type": "string"}, "roots": {"type": "array", "items": {"type": "string"}}, "regex": {"type": "boolean"}, "case_sensitive": {"type": "boolean"}, "context_before": {"type": "integer"}, "context_after": {"type": "integer"}, "limit": {"type": "integer"}}, ["query"]), operator_tools.repo_search_text),
        "northstar.archive_changed_files_zip": ("Create a changed-files zip artifact. Requires write/sudo mode.", schema({"output": {"type": "string"}}), operator_tools.archive_changed_files_zip),
        "northstar.archive_full_zip": ("Create a clean full source zip artifact. Requires write/sudo mode.", schema({"output": {"type": "string"}}), operator_tools.archive_full_zip),
        "northstar.archive_patch": ("Create a git diff patch artifact. Requires write/sudo mode.", schema({"output": {"type": "string"}, "timeout_sec": {"type": "integer"}}), operator_tools.archive_patch),
        "northstar.terminal_simulate_resize": ("Simulate fixed-footer terminal resize policies.", schema({"widths": {"type": "array", "items": {"type": "integer"}}, "heights": {"type": "array", "items": {"type": "integer"}}}), operator_tools.terminal_simulate_resize),
        "northstar.python_symbols": ("List top-level Python symbols/imports for a file.", schema({"path": {"type": "string"}}, ["path"]), operator_tools.python_symbols),
        "northstar.python_import_graph": ("Build a bounded Python import graph.", schema({"roots": {"type": "array", "items": {"type": "string"}}, "limit": {"type": "integer"}}), operator_tools.python_import_graph),
        "northstar.python_call_graph": ("Build a simple Python function call graph for one file.", schema({"path": {"type": "string"}}, ["path"]), operator_tools.python_call_graph),
        "northstar.repo_split_python_module": ("Move top-level Python symbols to another module. Requires write/sudo mode.", schema({"source": {"type": "string"}, "target": {"type": "string"}, "symbols": {"type": "array", "items": {"type": "string"}}, "apply": {"type": "boolean"}}, ["source", "target", "symbols"]), operator_tools.repo_split_python_module),
        "northstar.validate_no_legacy": ("Scan text files for denied legacy tokens.", schema({"deny": {"type": "array", "items": {"type": "string"}}, "roots": {"type": "array", "items": {"type": "string"}}, "limit": {"type": "integer"}}), operator_tools.validate_no_legacy),
        "northstar.validate_import_cycles": ("Detect simple Python import cycles for internal modules.", schema({"roots": {"type": "array", "items": {"type": "string"}}, "limit": {"type": "integer"}, "internal_prefix": {"type": "string"}}), operator_tools.validate_import_cycles),
        "northstar.validate_line_count": ("Report oversized source files above a line threshold.", schema({"roots": {"type": "array", "items": {"type": "string"}}, "max_lines": {"type": "integer"}}), operator_tools.validate_line_count),
        "northstar.status": ("Return AI bridge, Suite and repository status without mutating the workspace.", schema(), status.status),
        "northstar.operator_snapshot": ("Return combined status/logs/dataset/operator-memory snapshot.", schema({"logs_limit": {"type": "integer"}, "dataset_limit": {"type": "integer"}}), status.operator_snapshot),
        "northstar.operator_note_append": ("Append an operator note to .takesome/ai-bridge/notes and current-flow.md.", schema({"title": {"type": "string"}, "note": {"type": "string"}, "content": {"type": "string"}, "phase": {"type": "string"}, "task_id": {"type": "string"}, "tags": {"type": "array", "items": {"type": "string"}}}), memory.note_append),
        "northstar.operator_note_read": ("Read recent operator notes and current-flow metadata.", schema({"limit": {"type": "integer"}, "max_bytes": {"type": "integer"}, "include_current_flow": {"type": "boolean"}}), memory.note_read),
        "northstar.operator_state_get": ("Read JSON operator state from .takesome/ai-bridge/state.", schema({"namespace": {"type": "string"}, "key": {"type": "string"}}), memory.state_get),
        "northstar.operator_state_set": ("Write JSON operator state. Requires write mode.", schema({"namespace": {"type": "string"}, "key": {"type": "string"}, "value": {}}, ["key", "value"]), memory.state_set),
        "northstar.operator_cache_get": ("Read operator cache entry from .takesome/ai-bridge/cache.", schema({"namespace": {"type": "string"}, "key": {"type": "string"}}, ["key"]), memory.cache_get),
        "northstar.operator_cache_set": ("Write operator cache entry. Requires write mode.", schema({"namespace": {"type": "string"}, "key": {"type": "string"}, "value": {}}, ["key", "value"]), memory.cache_set),
        "northstar.operator_scratch_read": ("Read a scratch markdown draft.", schema({"name": {"type": "string"}, "max_bytes": {"type": "integer"}}, ["name"]), memory.scratch_read),
        "northstar.operator_scratch_write": ("Write a scratch markdown draft. Requires write mode.", schema({"name": {"type": "string"}, "content": {"type": "string"}}, ["name", "content"]), memory.scratch_write),
        "northstar.operator_task_record": ("Create or refresh a durable task record under .takesome/ai-bridge/tasks. Requires write mode.", schema({"task_id": {"type": "string"}, "title": {"type": "string"}, "task": {"type": "string"}, "intent": {"type": "string"}, "status": {"type": "string"}, "phase": {"type": "string"}, "priority": {"type": "string"}, "source": {"type": "string"}, "tags": {"type": "array", "items": {"type": "string"}}, "constraints": {}, "requested_output": {}, "state_snapshot": {}, "summary": {"type": "string"}}), memory.task_record),
        "northstar.operator_task_update": ("Append a structured event/state delta to a task record. Requires write mode.", schema({"task_id": {"type": "string"}, "title": {"type": "string"}, "status": {"type": "string"}, "phase": {"type": "string"}, "event_type": {"type": "string"}, "summary": {"type": "string"}, "diagnostics": {}, "next_actions": {}, "state_delta": {}, "engine_state_delta": {}, "artifacts": {}, "knowledge_links": {}}), memory.task_update),
        "northstar.operator_task_snapshot": ("Read current task, recent tasks and project knowledge memory.", schema({"limit": {"type": "integer"}, "knowledge_limit": {"type": "integer"}, "include_events": {"type": "boolean"}}), memory.task_snapshot),
        "northstar.operator_knowledge_update": ("Record a durable project knowledge item linked to tasks/artifacts. Requires write mode.", schema({"knowledge_id": {"type": "string"}, "type": {"type": "string"}, "entry_type": {"type": "string"}, "subject": {"type": "string"}, "title": {"type": "string"}, "summary": {"type": "string"}, "content": {"type": "string"}, "confidence": {"type": "string"}, "task_id": {"type": "string"}, "tags": {"type": "array", "items": {"type": "string"}}, "engine_domains": {"type": "array", "items": {"type": "string"}}, "artifacts": {}, "evidence": {}, "next_actions": {}}), memory.knowledge_update),
        "northstar.operator_knowledge_read": ("Read recent project knowledge items from .takesome/ai-bridge/knowledge.", schema({"limit": {"type": "integer"}}), memory.knowledge_read),
        "northstar.operator_current_state": ("Collect compact current North Star/Suite/dataSet/operator state without mutating memory.", schema({"artifact_limit": {"type": "integer"}}), memory.current_state),
        "northstar.operator_agent_status": ("Read the live serverBridge AI agent footer/status snapshot from .takesome/ai-bridge/state/agent-status.json.", schema(), memory.agent_status),
        "northstar.operator_memory_maintain": ("Prune old generated operator memory and refresh current-state knowledge. Requires write mode unless dry_run + refresh_current=false.", schema({"dry_run": {"type": "boolean"}, "refresh_current": {"type": "boolean"}, "max_tasks": {"type": "integer"}, "max_knowledge": {"type": "integer"}, "max_notes": {"type": "integer"}, "max_cache_items_per_namespace": {"type": "integer"}, "max_scratch_items": {"type": "integer"}, "artifact_limit": {"type": "integer"}}), memory.memory_maintain),
        "northstar.read_text": ("Read a whitelisted text file or list a whitelisted directory.", schema({"path": {"type": "string"}, "max_bytes": {"type": "integer"}}, ["path"]), repo.read_text),
        "northstar.read_log": ("Read a recent log by repository-relative path.", schema({"path": {"type": "string"}, "max_bytes": {"type": "integer"}}, ["path"]), repo.read_text),
        "northstar.search_text": ("Search whitelisted repository text roots.", schema({"query": {"type": "string"}, "roots": {"type": "array", "items": {"type": "string"}}, "limit": {"type": "integer"}, "regex": {"type": "boolean"}, "case_sensitive": {"type": "boolean"}}, ["query"]), repo.search_text),
        "northstar.list_tree": ("List a shallow repository tree for whitelisted roots.", schema({"path": {"type": "string"}, "max_depth": {"type": "integer"}, "limit": {"type": "integer"}}), repo.list_tree),
        "northstar.write_text": ("Write a project text file with backup. Requires write mode.", schema({"path": {"type": "string"}, "content": {"type": "string"}, "create_parents": {"type": "boolean"}}, ["path", "content"]), repo.write_text),
        "northstar.delete_path": ("Delete a repository-relative project file or directory. Requires write mode; directories require recursive=true.", schema({"path": {"type": "string"}, "recursive": {"type": "boolean"}, "dry_run": {"type": "boolean"}}, ["path"]), repo.delete_path),
        "northstar.patch_preview": ("Inspect a changed-files patch zip without applying it.", schema({"patch_path": {"type": "string"}}, ["patch_path"]), repo.patch_preview),
        "northstar.apply_changed_files_zip": ("Apply a changed-files patch zip with backups. Requires write mode.", schema({"patch_path": {"type": "string"}}, ["patch_path"]), repo.apply_changed_files_zip),
        "northstar.latest_incident": ("Read latest Suite incident handoff files.", schema({"max_bytes": {"type": "integer"}}), repo.latest_incident),
        "northstar.list_logs": ("List recent build/run/incident logs.", schema({"limit": {"type": "integer"}}), repo.list_logs),
        "northstar.git_status": ("Return git status --short.", schema(), repo.git_status),
        "northstar.bridge_restart": ("Run safe local AI bridge restart helper. Commands: status, stop-origin, wait-down, wait-up.", schema({"command": {"type": "string"}, "host": {"type": "string"}, "port": {"type": "integer"}, "timeout": {"type": "number"}, "wait_sec": {"type": "number"}, "dry_run": {"type": "boolean"}}), bridge_restart.bridge_restart),
        "northstar.bridge_restart_sequence": ("Run safe bounded local-origin restart sequence: status -> stop-origin -> wait-down. Requires write mode.", schema({"host": {"type": "string"}, "port": {"type": "integer"}, "timeout": {"type": "number"}, "wait_sec": {"type": "number"}, "dry_run": {"type": "boolean"}}), bridge_restart.bridge_restart_sequence),
        "northstar.bridge_reload_origin": ("Schedule a safe detached local-origin reload for the current AI bridge HTTP origin. Requires write mode; never stops cloudflared.", schema({"host": {"type": "string"}, "port": {"type": "integer"}, "timeout": {"type": "number"}, "wait_sec": {"type": "number"}, "delay_sec": {"type": "number"}, "dry_run": {"type": "boolean"}}), bridge_restart.bridge_reload_origin),
        "northstar.suite_actions": ("Ask SuiteRegistry for available Suite actions.", schema({"timeout_sec": {"type": "integer"}}), lambda c, a: run_takesome(c, ["suite", "--list-actions", "--json"], max(5, min(int(a.get("timeout_sec", 60)), 300)))),
        "northstar.suite_command": ("Run an allow-listed Suite command.", schema({"command_id": {"type": "string"}, "timeout_sec": {"type": "integer"}, "requires_openai_key": {"type": "boolean"}, "allow_unlisted": {"type": "boolean"}}, ["command_id"]), suite_command),
        "northstar.dataset_status": ("Return dataSetDirectory status and newest archives/directories.", schema(), dataset.status),
        "northstar.dataset_list_archives": ("List zip archives under dataSetDirectory.", schema({"limit": {"type": "integer"}, "recursive": {"type": "boolean"}}), dataset.list_archives),
        "northstar.dataset_scan_archive": ("Scan one dataSetDirectory zip archive.", schema({"archive_path": {"type": "string"}, "limit": {"type": "integer"}, "include_samples": {"type": "boolean"}}, ["archive_path"]), dataset.scan_archive),
        "northstar.dataset_search_archives": ("Search archive names and whitelisted text members.", schema({"query": {"type": "string"}, "limit": {"type": "integer"}, "search_content": {"type": "boolean"}, "case_sensitive": {"type": "boolean"}}, ["query"]), dataset.search_archives),
        "northstar.dataset_read_archive_member": ("Read a whitelisted text member from a zip.", schema({"archive_path": {"type": "string"}, "member": {"type": "string"}, "max_bytes": {"type": "integer"}}, ["archive_path", "member"]), dataset.read_archive_member),
        "northstar.dataset_materialize_archives": ("Extract dataset archives into .takesome/dataSet/extracted, then delete archive ingest objects by default. Requires write mode.", schema({"limit": {"type": "integer"}, "force": {"type": "boolean"}, "keep_archives": {"type": "boolean"}, "delete_archives": {"type": "boolean"}}), dataset.materialize_archives),
        "northstar.dataset_purge_archives": ("Delete dataSet .zip ingest objects that already have materialized extracted manifests. Requires write mode.", schema({"limit": {"type": "integer"}, "dry_run": {"type": "boolean"}}), dataset.purge_materialized_archives),
        "northstar.dataset_browse_directories": ("Browse materialized dataSet directories with logic scores, key files and extension stats.", schema({"path": {"type": "string"}, "depth": {"type": "integer"}, "limit": {"type": "integer"}, "max_files": {"type": "integer"}, "profile": {"type": "boolean"}}), dataset.browse_directories),
        "northstar.dataset_profile_directory": ("Profile one materialized dataSet directory as a reference corpus candidate.", schema({"path": {"type": "string"}, "max_files": {"type": "integer"}, "sample_limit": {"type": "integer"}}), dataset.profile_directory),
        "northstar.dataset_search_logic": ("Search materialized dataSet directories with logic-aware ranking.", schema({"query": {"type": "string"}, "path": {"type": "string"}, "limit": {"type": "integer"}, "case_sensitive": {"type": "boolean"}}), dataset.search_logic),
        "northstar.dataset_search_directories": ("Search materialized dataset directories first.", schema({"query": {"type": "string"}, "limit": {"type": "integer"}, "case_sensitive": {"type": "boolean"}}, ["query"]), dataset.search_directories),
        "northstar.dataset_rebuild_index": ("Rebuild directory-first dataset index. Requires write mode.", schema(), dataset.rebuild_index),
        "northstar.openai_key_status": ("Return OpenAI API key availability without revealing it.", schema(), lambda c, a: openai_status(c)),
        "northstar.openai_key_require": ("Ensure an OpenAI API key exists.", schema(), lambda c, a: {"ok": True, **openai_status(c)} if openai_env(c, True) else {}),
        "northstar.openai_key_forget": ("Delete cached OpenAI API key. Requires write mode or interactive.", schema(), lambda c, a: forget_key(c)),
        "northstar.workflow_spiral": ("Run a bounded synchronous observe/analyze/verify/build spiral workflow with persistent notes/state/cache.", schema({"task": {"type": "string"}, "task_id": {"type": "string"}, "phases": {"type": "array", "items": {"type": "string"}}, "include_build": {"type": "boolean"}, "include_runtime": {"type": "boolean"}, "materialize_dataset": {"type": "boolean"}, "browse_dataset": {"type": "boolean"}, "dataset_path": {"type": "string"}, "dataset_query": {"type": "string"}, "query": {"type": "string"}, "dataset_limit": {"type": "integer"}, "dataset_browser_depth": {"type": "integer"}, "dataset_browser_limit": {"type": "integer"}, "dataset_browser_max_files": {"type": "integer"}, "dataset_profile_max_files": {"type": "integer"}, "dataset_profile_sample_limit": {"type": "integer"}, "dataset_search_limit": {"type": "integer"}, "logs_limit": {"type": "integer"}, "max_steps": {"type": "integer"}, "timeout_sec": {"type": "integer"}, "stop_on_failure": {"type": "boolean"}, "allow_unlisted": {"type": "boolean"}, "force_dataset": {"type": "boolean"}, "case_sensitive": {"type": "boolean"}}), workflow.workflow_spiral),
    }
    tools = {name: ToolSpec(name, desc, spec_schema, bind(fn)) for name, (desc, spec_schema, fn) in specs.items()}
    tools.update(build_project_tool_specs(ctx))
    return tools
