from __future__ import annotations

import argparse
import binascii
import json
from pathlib import Path
from typing import Any



def import_ui_fonts_command(root: Path, ns: argparse.Namespace) -> int:
    """Build the runtime editor.yft dictionary from local font source files.

    The UI provider must not open raw TTF/OTF files. This command is the local
    importer bridge: it reads the declarative import manifest, embeds face bytes
    into a runtime .yft JSON dictionary, and writes it to assets/ui/fonts. The
    Aurelia provider already accepts this runtime file directly and also accepts
    a binary NEF8 .yft when AssetManager/listfile tooling packs the same body.
    """
    manifest_path = Path(ns.manifest) if ns.manifest else engine_core_root(root) / "assets" / "ui" / "fonts" / "editor.yft.import.json"
    if not manifest_path.is_absolute():
        manifest_path = root / manifest_path
    out_path = Path(ns.output) if ns.output else engine_core_root(root) / "assets" / "ui" / "fonts" / "editor.yft"
    if not out_path.is_absolute():
        out_path = root / out_path

    if not manifest_path.exists():
        print(f"[ERROR] UI font import manifest not found: {manifest_path}")
        return 2

    manifest = json.loads(manifest_path.read_text(encoding="utf-8-sig"))
    faces: list[dict[str, Any]] = []
    missing: list[str] = []
    optional_missing: list[str] = []
    for face in manifest.get("faces", []):
        source = str(face.get("source", "")).strip()
        optional = bool(face.get("optional", False))
        if not source:
            target = optional_missing if optional else missing
            target.append(f"{face.get('id', '<unnamed>')}: missing source")
            continue
        source_path = engine_core_root(root) / source
        if not source_path.exists():
            target = optional_missing if optional else missing
            target.append(str(source_path.relative_to(root)))
            continue
        blob = source_path.read_bytes()
        faces.append({
            "id": face.get("id", source_path.stem),
            "family": face.get("family", source_path.stem),
            "style": face.get("style", "normal"),
            "weight": int(face.get("weight", face.get("default_weight", 400))),
            "weight_range": face.get("weight_range"),
            "source_ref": f"{manifest.get('target_asset', 'ui/fonts/editor.yft')}@{face.get('id', source_path.stem)}",
            "source_blob_ref": f"{manifest.get('target_asset', 'ui/fonts/editor.yft')}@{face.get('id', source_path.stem)}#blob",
            "source_blob_hex": binascii.hexlify(blob).decode("ascii"),
            "unicode_ranges": face.get("unicode_ranges", infer_unicode_ranges(face)),
            "coverage": face.get("coverage", face.get("roles", infer_unicode_ranges(face))),
            "features": face.get("features", ["kern", "liga", "mark", "mkmk"]),
            "variations": face.get("variations", []),
            "atlas_policy": manifest.get("runtime", {}).get("atlas_policy", "provider_owned_msdf_or_sdf"),
        })

    doc = {
        "schema": "newengine.font_dictionary.yft.v1",
        "asset_ref": manifest.get("target_asset", "ui/fonts/editor.yft"),
        "faces": faces,
        "fallback_stack": manifest.get("runtime", {}).get("fallback_stack", []),
        "diagnostics": [
            "generated by python -m noesis suite import-ui-fonts",
            "runtime .yft contains imported face bytes; UI provider does not open raw TTF/OTF files",
        ],
    }
    if missing:
        doc["diagnostics"].append("missing required local source font(s): " + ", ".join(missing))
    if optional_missing:
        doc["diagnostics"].append("missing optional fallback font(s): " + ", ".join(optional_missing))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"[OK] Runtime UI font dictionary written: {out_path}")
    print(f"[INFO] Embedded face blobs: {len(faces)}")
    if optional_missing:
        print("[WARN] Missing optional fallback font inputs; affected scripts will use explicit degraded fallback:")
        for item in optional_missing:
            print(f"[WARN]   {item}")
    if missing:
        print("[WARN] Missing required local font inputs; HarfBuzz will stay fallback until at least one face has bytes:")
        for item in missing:
            print(f"[WARN]   {item}")
        return 1
    return 0


def infer_unicode_ranges(face: dict[str, Any]) -> list[str]:
    haystack = " ".join(str(face.get(key, "")) for key in ("id", "family", "display_name", "roles", "usage_policy")).lower()
    ranges: list[str] = []
    if any(token in haystack for token in ("inter", "granic", "body", "editor", "latin")):
        ranges.extend(["latin", "latin_ext", "cyrillic"])
    if any(token in haystack for token in ("cjk", "noto sans cjk", "jp", "sc", "tc", "kana", "hangul")):
        ranges.extend(["cjk", "kana", "hangul"])
    if any(token in haystack for token in ("arabic", "hebrew", "naskh", "rtl")):
        ranges.extend(["arabic", "hebrew", "rtl"])
    if any(token in haystack for token in ("emoji", "color emoji")):
        ranges.append("emoji")
    if any(token in haystack for token in ("symbol", "icons")):
        ranges.append("symbols")
    return list(dict.fromkeys(ranges or ["latin"]))
